export default{
    //获取搜索关键字
    getSearchKeyWord(state,payload)
    {
        state.keyword=payload.keyword;
    },
    getSearchList(state,payload)
    {
      state.searchList=payload.searchList
    },
    //获取歌曲URL
    getSongUrl(state,payload)
    {
        state.songUrl=payload.url;
        state.songId=payload.songId
    },
    //获取歌曲封面
    getAlbumImg(state,payload)
    {
        state.albumImgUrl=payload.albumImgUrl
    },
    //获取推荐页面下的歌手中歌手列表
    getSingerList(state,payload)
    {
        state.singerLists=payload.singers;
    },
    /*获取登录状态*/
    changeLoginType(state,payload)
    {
        state.loginType=payload.loginType;
    },
    userMsg(state,payload)
    {
        state.userMsg=payload.userMsg;
    },
    /**********更改loading组件的显示*****************************/
    changeLoadingStatus(state,payload)
    {
        state.loading=payload.loadStatus
    },
    /******************获取用户歌单信息*******************/
    getUserSongListMsg(state,payload)
    {
        state.userSongListMsg=payload.userSongListMsg
    },
    //更改用户播放模式
    changePlayMode(state,payload) {
        state.playMode=payload.playMode
    },
    //更改当前播放歌曲
    changeCurrentSong(state,payload)
    {
        state.currentSong=payload.song;
    },
    //更改当前播放歌曲索引
    changeCurrentSongIndex(state,payload)
    {
        state.currentSongIndex=payload.songIndex;
    },
    //更改当前用户播放列表中
    changePlayList(state,payload)
    {
        state.playList.push(payload.song)
    },
    //更改歌词数组
    changeLyricList(state,payload)
    {
        state.lyricList=payload.lyricList
    },
    //更改某一句歌词
    changeLineLyric(state,payload)
    {
        state.lyric=payload.lineLyric
    },
    //更改歌单详细信息
    changePlayListDetail(state,payload)
    {
        state.playListDetail=payload.playListDetail
    },
    //飙升榜
    changeUpRanking(state,payload)
    {
        state.upRanking=payload.upRanking
    },
    //新歌榜
    changeNewRanking(state,payload)
    {
        state.newRanking=payload.newRanking
    },
    //原创帮
    changeOriginRanking(state,payload)
    {
        state.originRanking=payload.originRanking
    },
    //热歌榜
    changeHotRanking(state,payload)
    {
        state.hotRanking=payload.hotRanking
    },
    changeTest(state,payload)
    {
        state.test=payload.test;
    }
}